name: bytebank
description: A bytebank project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #adiciona o sqflite com o PATH dentro do APP
  sqflite:
  path:
  http:
  http_interceptor:

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  cool_alert: ^1.1.0
  animated_card: ^2.0.0
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  #adiciona a pasta de IMAGES e todos seus item como um ASSET do FLUTTER
  assets:
    - assets/images/
  
  